jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Push to GitHub
        run: |
          git config --global user.name "Tharindu Ishan"
          git config --global user.email "ishanthari96@gmail.com"
          git push https://${{ secrets.PAT_SECRET }}@github.com/tharindu-ishan/repo.git
